### ISSUE TITLE
Styling regulatory interactions

### ISSUE THREAD

**Issue by ctrlaltaf** [Reed-CompBio/protein-weaver#109]
How do we visualize these regulatory interactions in conjunction with the visualization we have?

**Comment by oliverfanderson** [comment]
Ideas:
- What to do with nodes with only "gene_name" (i.e. no protein in our original PPI)? Display warning that this is a TF/gene only?
- Directed edges with arrows
- Could use dashed or dotted lines to indicate Reg edge type
- Edges toggleable/alternate view for Reg edges
- Inhibitory vs Activation edges: blunt ends for inhibition, arrow tips for activation.
   - Add property to regulatory edges
   - Get property when clicked (tooltip in viz or on sidebar)
   - Could color code alternatively/as well

**Comment by oliverfanderson** [comment]
To do:

- [ ] Add legend describing new Reg edge types
- [ ] Add blunt or arrow tip
- [ ] Consider do we want red edges? Other color ideas for the edges?
