### ISSUE TITLE
Work on Deploying the Website

### ISSUE THREAD

**Issue by annaritz** [Reed-CompBio/protein-weaver#13]
look into Digital Ocean. We should be able to use the Rosalind droplet but add a new virtual environment w/ a new URL.

**Comment by annaritz** [comment]
We have a plan, but want to wait to deploy the website until we have all species in the DB.

**Comment by annaritz** [comment]
Let's plan to have a version of the website live by mid-November (about a month from now).

**Comment by oliverfanderson** [comment]
- [ ] Neo4j
   (a) virtual server w/ localhost
   (b) virtual server w/ live url
- [ ] Import data (bash script)
- [ ] GitHub frontend
- [ ] Backend/frontend
- [ ] Load balancer config
- [ ] Point to correct url
- [ ] Cloudflare

**Comment by ctrlaltaf** [comment]
closed with v1.0-stable release
