### ISSUE TITLE
if source node is in GO term, network is incorrect

### ISSUE THREAD

**Issue by annaritz** [Reed-CompBio/protein-weaver#18]
Yen's shortest path returns the source node and no other edges/paths.

**Comment by ctrlaltaf** [comment]
@oliverfanderson I think it should be possible (need to check if they may or may not have the same name as ProPro).

**Comment by ctrlaltaf** [comment]
As of this comment, our plan is the following

- Represent the native graph as an undirected graph right before we go live with the website
- For now, use the following code to only change the in-memory representation of the graph
`CALL gds.beta.graph.relationships.toUndirected(
'myGraph',
{relationshipType: 'ProPro', mutateRelationshipType: 'ProProUndirected'}
)
YIELD
inputRelationships, relationshipsWritten`
