### ISSUE TITLE
Add traffic logging

### ISSUE THREAD

**Issue by annaritz** [Reed-CompBio/protein-weaver#36]
At some point make sure we have some type of traffic logging (e.g., # of users, # of queries/exports, etc.

**Comment by oliverfanderson** [comment]
https://analytics.google.com/analytics/web/provision/#/provision

More than likely we will use some version of Google Analytics to track this type of information, we just have to be sure that we can track custom events like queries and exports.

**Comment by oliverfanderson** [comment]
Cloudflare gives us some analytics that provide basic usage data.
