### ISSUE TITLE
Add B. Subtilis data

### ISSUE THREAD

**Issue by annaritz** [Reed-CompBio/protein-weaver#39]
Add PPI and regulatory interaction data.

**Comment by annaritz** [comment]
Here's one source: SubtiWiki has an [exports page](http://subtiwiki.uni-goettingen.de/v4/exports).

From their [paper](https://academic.oup.com/nar/article/50/D1/D875/6401899): "Currently, we have expanded the data to >5950 and >2660 experimentally validated regulatory and protein–protein interactions, respectively"

**Comment by annaritz** [comment]
Here's a list of GO terms for B. subtilis: [https://bsubcyc.org/BSUB/class-tree?object=Gene-Ontology-Terms](https://bsubcyc.org/BSUB/class-tree?object=Gene-Ontology-Terms). From BSubCyc.

**Comment by annaritz** [comment]
What we just went through:
- We looked up _all_ the B. subtilis GO annotations in AmiGO.
- We downloaded that file, there were full names & UniProt IDs. 
- If uniprot or bsubcyc has a Uniprot-to-BSUB mapping or a common-name to identifier mapping, we should be OK.

**Comment by oliverfanderson** [comment]
Our GO annotations file seems to only have the entry for GO qualifier for about 50 of the entries, the rest are blank. I will move forward with this for now but either we may lack qualifiers for some of the B sub entries or we need to find an additional data source.

**Comment by oliverfanderson** [comment]
We have the ability to add a symbol and common name search for the B. Subtilis data since we have two multiple naming conventions. E.g. Leucine--tRNA ligase & LeuS.
