### ISSUE TITLE
Adding evidence/pubmed links to edges as properties

### ISSUE THREAD

**Issue by annaritz** [Reed-CompBio/protein-weaver#42]
Right now we have that information but it's not available to the user. Can we add it in the edges, or in the sidepanel?

**Comment by oliverfanderson** [comment]
We have this information for D. melanogaster but currently not the other species. We have added it to the underlying database but have not yet presented it on the frontend for users to see.

**Comment by oliverfanderson** [comment]
Bumping because this was suggested as part of our paper feedback

**Comment by oliverfanderson** [comment]
- TXID7227: Has pubmed ID as a property
- TXID7955 & TXID224308: Has evidence type as a property (experimental, textmined, etc.)

**Comment by oliverfanderson** [comment]
For links with this format: 7955.ENSDARP00000000004/7955.ENSDARP00000013291
- Example URL: https://string-db.org/interaction/7955.ENSDARP00000000004/7955.ENSDARP00000013291

For PubMed ID: 19004873
- Example URL: pubmed.ncbi.nlm.nih.gov/19004873

1. TXID7227: uses PubMed IDs
2. TXID224308: uses string-db
3. TXID7955: PubMed if available string-db when not (dynamically rendered based on source property)

**Comment by oliverfanderson** [comment]
- [ ] Add to datasets
- [ ] Import into database
- [ ] Access evidence property in client
- [ ] Dynamically render link in client based on species and evidence type
