### ISSUE TITLE
"Cannot reach site error"

### ISSUE THREAD

**Issue by ctrlaltaf** [Reed-CompBio/protein-weaver#59]
Using the Reed Wifi, if I omit the https in the URL, I get a web page blocked error with category parked. The SSL certificates are verified for the URL proteinweaver.reedcompbio.org.

**Comment by oliverfanderson** [comment]
I don't know if this is exactly the same problem but this thread might be of interest to you: https://forums.cpanel.net/threads/ssl-on-parked-domain.619663/

**Comment by ctrlaltaf** [comment]
closed Reed wifi's firewall marked out site parked on certain sites
