### ISSUE TITLE
Inconsistent error messages between the two methods

### ISSUE THREAD

**Issue by annaritz** [Reed-CompBio/protein-weaver#67]
When trying this query in B. Subtilis, the k-unique paths reports and error message but the k-unique nodes returns an empty graph. These should have consistent behaviors.

![Screenshot 2024-02-02 at 8 57 17 PM](https://github.com/Reed-CompBio/protein-weaver/assets/1457970/14fff569-5df3-473a-a861-d1caf321a36a)

**Comment by oliverfanderson** [comment]
Think the source of the bug is in the routes.js file.

**Comment by ctrlaltaf** [comment]
closed by 835a88f0c80d5f790f8223b40c100bf352b2a1c4
