### ISSUE TITLE
Add more informative error messages

### ISSUE THREAD

**Issue by annaritz** [Reed-CompBio/protein-weaver#68]
When there is an error, the message should report why the network is not shown. Is there an error with the protein name or GO term? Are there no paths that connect the query node to the GO-annotated nodes? are there any GO-annotated nodes for that species? etc.

**Comment by annaritz** [comment]
Also see #67 while we are addressing this one.

**Comment by ctrlaltaf** [comment]
Would appreciate testing the branch `error-messages` 6f1a9169801e4611c97cc62fc79c5e352c4ef47b
Currently these are the following error messages that appear

- Source protein not found [1](http://localhost:5173/query?mode=path&species=txid7227&protein=12323&goTerm=protein+complex+involved+in+cell+adhesion&k=3) , [2](http://localhost:5173/query?mode=node&species=txid224308&protein=vcxc&goTerm=leukocyte+cell-cell+adhesion&k=3)
- GO term not found [1](http://localhost:5173/query?mode=path&species=txid224308&protein=AtpD&goTerm=asdasdas&k=3) , [2](http://localhost:5173/query?mode=node&species=txid7955&protein=AtpD&goTerm=dsa&k=3)
- No direct proteins connected to GO term [1](http://localhost:5173/query?mode=node&species=txid224308&protein=DivIVA&goTerm=protein+complex+involved+in+cell+adhesion&k=3) , [2](http://localhost:5173/query?mode=path&species=txid224308&protein=DivIVA&goTerm=protein+complex+involved+in+cell+adhesion&k=3)
- No paths connecting protein of interest to nearby proteins labeled with the GO term [1](http://localhost:5173/query?mode=node&species=txid7955&protein=Q5RIV1&goTerm=leukocyte+cell-cell+adhesion&k=4) , [2](http://localhost:5173/query?mode=path&species=txid7955&protein=Q5RIV1&goTerm=leukocyte+cell-cell+adhesion&k=4)

**Comment by ctrlaltaf** [comment]
closed and tested
