### ISSUE TITLE
Add pro-GO relationships among parent GO terms

### ISSUE THREAD

**Issue by annaritz** [Reed-CompBio/protein-weaver#69]
protein annotations in GO should include the most specific GO term as well as that term's parents in the ontology. We currently annotate the protein to the most specific GO term, but do not include ancestral GO term links.

**Comment by oliverfanderson** [comment]
I noticed when getting GO annotations for Zebrafish that this API can export all GO annotations for a species with an "include descendants" tag, which may be what we are looking for here.

https://www.ebi.ac.uk/QuickGO/annotations

**Comment by oliverfanderson** [comment]
Exported all ancestor GO terms for the 3 existing species (txid7227, txid7955, txid224308).
