### ISSUE TITLE
multiple UniProt IDs generate multiple source nodes in the network

### ISSUE THREAD

**Issue by annaritz** [Reed-CompBio/protein-weaver#70]
See, for example, [this link Draxin in Zebrafish](https://proteinweaver.reedcompbio.org/query?mode=path&species=txid7955&protein=Draxin+&goTerm=Wnt+signaling+pathway&k=5). This is because there are three UniProt IDs mapped to Draxin.

**Comment by oliverfanderson** [comment]
Could use the "alt_name" parameter (longer names), the" alt_name" seems to be distinct between the proteins that have the same "name"
