### ISSUE TITLE
Frontend Error/UX issues

### ISSUE THREAD

**Issue by ctrlaltaf** [Reed-CompBio/protein-weaver#71]
- [x] In the live server, the loading bar disappears after the API response is fetched but before the parsing tools have not completed the data format generation for cytoscapejs (leading to an awkward gap between querying and the graph appearing)
- [x] K-unique nodes do not output anything for the following queries [1](https://proteinweaver.reedcompbio.org/query?mode=node&species=txid7955&protein=Dragon&goTerm=mechanosensitive+monoatomic+ion+channel+activity&k=7) [2](https://proteinweaver.reedcompbio.org/query?mode=node&species=txid224308&protein=NupO&goTerm=Ino80+complex&k=7)
- [x] About page 'library' div is not left aligned
- [x] Nav bar doesnt stretch to fill the width (noticeable on mobile)

**Comment by oliverfanderson** [comment]
- [ ] Fix footer on mobile
