### ISSUE TITLE
Add feature to automatically create a github issue when encountering a wrong query

### ISSUE THREAD

**Issue by ctrlaltaf** [Reed-CompBio/protein-weaver#94]
Suppose a user queries something and they expect a certain result but it ends up not being the same as their expected result. I would be convenient to add a feature that when an error appears, allow users the ability to autoredirect to the github's issue page and submit an issue

**Comment by oliverfanderson** [comment]
Produce link to this upon query error: https://github.com/Reed-CompBio/protein-weaver/issues/new

**Comment by oliverfanderson** [comment]
added link to issues page on query error
